# Generated by Django 5.2 on 2025-05-04 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_rename_pubicada_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_publicada',
            field=models.DateField(default=datetime.datetime(2025, 5, 4, 14, 48, 56, 41120)),
        ),
    ]
