# Generated by Django 5.2 on 2025-05-04 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_fotografia_data_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data_publicada',
            field=models.DateField(default=datetime.datetime(2025, 5, 4, 14, 50, 0, 512068)),
        ),
    ]
